name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-waka-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v2.0.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}